pipeline{
  agent any
  
  stages{
     stage("Build"){
       steps{
	    // Get some code from a GitHub repository
            git 'https://github.com/edmitrenko/jenkins-java-app2.git/'
            
            // Run Maven on a Unix agent
            sh "./mvnw clean install"
            }
            }
			
     stage("Deploy"){
       steps{
          deploy adapters: [tomcat9(credentialsId: 'jenkins-to-tomcat', path: '', url: 'http://ec2-13-48-30-64.eu-north-1.compute.amazonaws.com:8080')], contextPath: null, onFailure: false, war: '**/*.war'
            }
          }
        }
      }